name: org-checkstyle
on:
  workflow_call:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Verify (includes Checkstyle)
        run: mvn -B -DskipTests verify
