name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          # Configure these if you add distributionManagement to POMs
          server-id: your-registry
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build & Deploy
        run: mvn -B -DskipTests deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
